name: Starter Workflow Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: List files in current directory
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run:
          echo What is in this directory?
          ls -a
          echo What is the current directory?
          #pwd
