name: CI
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

#on: [push]


jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install, build
        run: |
          # 👇 update npm to the latest version
          npm install -g npm@latest

          # 👇 clean npm cache
          npm cache clean --force

          # 👇 delete node modules and package-lock.json 
          npm rm -rf node_modules && rm package-lock.json

          # 👇 retry installing dependencies
          npm install
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          lhci autorun


  build-on-updatereadme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      
      #IMPLEMENT THE CACHE PROPERLY!!!!!!!!
      #- name: Setup a Cache for lighthouse
      #  uses: actions/cache@v1.2.1
      #  with:
        # A directory to store and save the cache
      #    path: ~/.lhcache
        # An explicit key for restoring and saving the cache
      #    key: TST
       #   restore-keys: TST
          
          
      
    
    #  - name: Get information about environment
     #   shell: bash
      #  run: sh ./gha-script.sh 
