name: Starter Workflow Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Audit URLS using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://akademsubotnik.github.io/
      
      - name: List files in current directory
        run: echo Hello, world!
        shell: bash
      
      - name: Run a multi-line script
        shell: bash
        run: sh ./gha-script.sh 
  

  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install && npm install -g @lhci/cli@0.11.x
          npm run build
          lhci autorun

